/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.com.colmeiatecnologia.EmailMarketing.view;


import br.com.colmeiatecnologia.EmailMarketing.control.ArquivoControl;
import br.com.colmeiatecnologia.EmailMarketing.control.view.TextAreaControl;
import br.com.colmeiatecnologia.EmailMarketing.model.EmailModel;
import br.com.colmeiatecnologia.EmailMarketing.model.MensagemModel;
import br.com.colmeiatecnologia.EmailMarketing.model.ThreadTimerModel;
import br.com.colmeiatecnologia.EmailMarketing.model.dao.DestinatarioDAO;
import br.com.colmeiatecnologia.EmailMarketing.model.dao.RemetenteDAO;
import br.com.colmeiatecnologia.EmailMarketing.model.dao.RemetenteDadosDAO;
import java.awt.Component;
import java.awt.Container;
import java.awt.Toolkit;
import java.awt.event.ContainerEvent;
import java.awt.event.ContainerListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Rogério Eduardo Pereira <rogerio@groupsofter.com.br>
 * @version 1.0
 */
public class Principal extends javax.swing.JFrame {

    /** Creates new form JanelaPrincipal */
    public Principal() {
        initComponents();
        addKeyAndContainerListenerRecursively(this);
        this.setLocationRelativeTo(null);
    }

    //BOTAO ESC E ENTER
    //LISTENERS DO FRAME
    //KEYLISTENER RECURSIVO (COLOCA EM TODOS OS COMPONENTES)
    private void addKeyAndContainerListenerRecursively(Component c) 
    {  
        try 
        {  
            c.addKeyListener((KeyListener) this);  
            if (c instanceof Container) 
            {  
                Container cont = (Container) c;  
                cont.addContainerListener((ContainerListener) this);  
                Component[] children = cont.getComponents();  
                for (int i = 0; i < children.length; i++) 
                {  
                    addKeyAndContainerListenerRecursively(children[i]);  
                }  
            }  
        } catch (Exception e) {  
            //Anuncie Aqui  
        }  
    }  
    
    //EVENTOS KEYLISTENER
    public void keyTyped(KeyEvent e) {}  
    public void keyReleased(KeyEvent e) {}  
    public void componentAdded(ContainerEvent e) {}  
    public void componentRemoved(ContainerEvent e) {}  
    public void keyPressed(KeyEvent e) 
    {
        //TECLA ESC
        if(e.getKeyCode() == KeyEvent.VK_ESCAPE)
        {
            
        }
        else if (e.getKeyCode() == KeyEvent.VK_ENTER)
        {
            
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        buscaArquivo = new javax.swing.JFileChooser();
        painelDadosRemetente = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        textoNomeRemetente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        textoEmailEnvio = new javax.swing.JTextField();
        painelConfiguracoesEmail = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        textoHostSmtp = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        checkAutenticacao = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        textoUsuario = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        textoSenha = new javax.swing.JTextField();
        textoPorta = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        textoMaximoEnvio = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        textoAssunto = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        JScrollPane1 = new javax.swing.JScrollPane();
        textoMensagem = new javax.swing.JTextArea();
        botaoProcurarMensagem = new javax.swing.JButton();
        painelDestinatarios = new javax.swing.JPanel();
        botaoProcurarDestinatarios = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        textoDestinatarios = new javax.swing.JTextArea();
        botaoIniciarEnvio = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuCadastrar = new javax.swing.JMenu();
        menuCadastrarRemetente = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Email Marketing");
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/br/com/colmeiatecnologia/EmailMarketing/view/img/icone.png")));

        painelDadosRemetente.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Envio", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));

        jLabel1.setText("Nome");

        textoNomeRemetente.setPreferredSize(new java.awt.Dimension(14, 32));

        jLabel2.setText("E-mail Envio");

        textoEmailEnvio.setPreferredSize(new java.awt.Dimension(80, 32));

        painelConfiguracoesEmail.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Configurações Envio", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));

        jLabel3.setText("Host SMTP:");

        textoHostSmtp.setPreferredSize(new java.awt.Dimension(80, 32));

        jLabel4.setText("Porta");

        checkAutenticacao.setSelected(true);
        checkAutenticacao.setText("Autenticação SSL");

        jLabel5.setText("Usuário");

        textoUsuario.setPreferredSize(new java.awt.Dimension(80, 32));

        jLabel6.setText("Senha");

        textoSenha.setPreferredSize(new java.awt.Dimension(80, 32));

        textoPorta.setMinimumSize(new java.awt.Dimension(14, 32));
        textoPorta.setName(""); // NOI18N
        textoPorta.setPreferredSize(new java.awt.Dimension(14, 32));

        jLabel13.setText("Máximo Envios");

        textoMaximoEnvio.setPreferredSize(new java.awt.Dimension(14, 32));

        javax.swing.GroupLayout painelConfiguracoesEmailLayout = new javax.swing.GroupLayout(painelConfiguracoesEmail);
        painelConfiguracoesEmail.setLayout(painelConfiguracoesEmailLayout);
        painelConfiguracoesEmailLayout.setHorizontalGroup(
            painelConfiguracoesEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelConfiguracoesEmailLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelConfiguracoesEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelConfiguracoesEmailLayout.createSequentialGroup()
                        .addGroup(painelConfiguracoesEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(painelConfiguracoesEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textoPorta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textoHostSmtp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                            .addComponent(textoSenha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textoUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(painelConfiguracoesEmailLayout.createSequentialGroup()
                        .addGroup(painelConfiguracoesEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkAutenticacao)
                            .addGroup(painelConfiguracoesEmailLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textoMaximoEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        painelConfiguracoesEmailLayout.setVerticalGroup(
            painelConfiguracoesEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelConfiguracoesEmailLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelConfiguracoesEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(textoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelConfiguracoesEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(textoSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelConfiguracoesEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textoHostSmtp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelConfiguracoesEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(textoPorta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkAutenticacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelConfiguracoesEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(textoMaximoEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel7.setText("Assunto");

        textoAssunto.setPreferredSize(new java.awt.Dimension(80, 32));

        jLabel8.setText("Mensagem");

        textoMensagem.setColumns(20);
        textoMensagem.setLineWrap(true);
        textoMensagem.setWrapStyleWord(true);
        JScrollPane1.setViewportView(textoMensagem);

        botaoProcurarMensagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/colmeiatecnologia/EmailMarketing/view/img/zoom.png"))); // NOI18N
        botaoProcurarMensagem.setText("Procurar");
        botaoProcurarMensagem.setPreferredSize(new java.awt.Dimension(150, 32));
        botaoProcurarMensagem.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                botaoProcurarMensagemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelDadosRemetenteLayout = new javax.swing.GroupLayout(painelDadosRemetente);
        painelDadosRemetente.setLayout(painelDadosRemetenteLayout);
        painelDadosRemetenteLayout.setHorizontalGroup(
            painelDadosRemetenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDadosRemetenteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelDadosRemetenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelDadosRemetenteLayout.createSequentialGroup()
                        .addGroup(painelDadosRemetenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(painelConfiguracoesEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(painelDadosRemetenteLayout.createSequentialGroup()
                                .addGroup(painelDadosRemetenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(24, 24, 24)
                                .addGroup(painelDadosRemetenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(textoEmailEnvio, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                                    .addComponent(textoNomeRemetente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelDadosRemetenteLayout.createSequentialGroup()
                        .addGroup(painelDadosRemetenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(painelDadosRemetenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botaoProcurarMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textoAssunto, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelDadosRemetenteLayout.createSequentialGroup()
                        .addComponent(JScrollPane1)
                        .addContainerGap())))
        );
        painelDadosRemetenteLayout.setVerticalGroup(
            painelDadosRemetenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDadosRemetenteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelDadosRemetenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textoNomeRemetente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelDadosRemetenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textoEmailEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelConfiguracoesEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelDadosRemetenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(textoAssunto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelDadosRemetenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(botaoProcurarMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                .addContainerGap())
        );

        painelDestinatarios.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Destinatários", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));

        botaoProcurarDestinatarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/colmeiatecnologia/EmailMarketing/view/img/zoom.png"))); // NOI18N
        botaoProcurarDestinatarios.setText("Procurar");
        botaoProcurarDestinatarios.setPreferredSize(new java.awt.Dimension(150, 32));
        botaoProcurarDestinatarios.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                botaoProcurarDestinatariosActionPerformed(evt);
            }
        });

        textoDestinatarios.setColumns(20);
        textoDestinatarios.setLineWrap(true);
        textoDestinatarios.setToolTipText("");
        textoDestinatarios.setWrapStyleWord(true);
        jScrollPane2.setViewportView(textoDestinatarios);

        botaoIniciarEnvio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/colmeiatecnologia/EmailMarketing/view/img/dialog-accept.png"))); // NOI18N
        botaoIniciarEnvio.setText("Iniciar Envio");
        botaoIniciarEnvio.setPreferredSize(new java.awt.Dimension(150, 32));
        botaoIniciarEnvio.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                botaoIniciarEnvioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelDestinatariosLayout = new javax.swing.GroupLayout(painelDestinatarios);
        painelDestinatarios.setLayout(painelDestinatariosLayout);
        painelDestinatariosLayout.setHorizontalGroup(
            painelDestinatariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDestinatariosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelDestinatariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelDestinatariosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botaoProcurarDestinatarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(painelDestinatariosLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(botaoIniciarEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelDestinatariosLayout.setVerticalGroup(
            painelDestinatariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDestinatariosLayout.createSequentialGroup()
                .addComponent(botaoProcurarDestinatarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoIniciarEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        menuCadastrar.setText("Cadastrar");

        menuCadastrarRemetente.setText("Remetente");
        menuCadastrarRemetente.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                menuCadastrarRemetenteActionPerformed(evt);
            }
        });
        menuCadastrar.add(menuCadastrarRemetente);

        jMenuBar1.add(menuCadastrar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelDadosRemetente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelDestinatarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelDadosRemetente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelDestinatarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoProcurarDestinatariosActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botaoProcurarDestinatariosActionPerformed
    {//GEN-HEADEREND:event_botaoProcurarDestinatariosActionPerformed
        conteudoArquivo = new ArrayList<String>();
        conteudoArquivo = buscaArquivo(txtFilter);
       
        ArrayList<String> emailsvalidos = new ArrayList<String>();
        
        for(String email: conteudoArquivo)
        {
            if(EmailModel.validaEmail(email))
                emailsvalidos.add(email.trim().toLowerCase());
        }
        
        TextAreaControl.insereConteudo(textoDestinatarios, emailsvalidos);
    }//GEN-LAST:event_botaoProcurarDestinatariosActionPerformed

    private void botaoProcurarMensagemActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botaoProcurarMensagemActionPerformed
    {//GEN-HEADEREND:event_botaoProcurarMensagemActionPerformed
        conteudoArquivo = new ArrayList<String>();
        conteudoArquivo = buscaArquivo(htmlFilter);
        TextAreaControl.insereConteudo(textoMensagem, conteudoArquivo);
    }//GEN-LAST:event_botaoProcurarMensagemActionPerformed

    private void botaoIniciarEnvioActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botaoIniciarEnvioActionPerformed
    {//GEN-HEADEREND:event_botaoIniciarEnvioActionPerformed
        RemetenteDadosDAO remetente = obtemDadosRemetente();
        remetente.setDestinatarios(obtemDestinatarios());
        
        MensagemModel mensagem = new MensagemModel(textoAssunto.getText(), textoMensagem.getText());
        
        limpaTela();

        new ThreadTimerModel(remetente, mensagem, this);
    }//GEN-LAST:event_botaoIniciarEnvioActionPerformed

    private void menuCadastrarRemetenteActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_menuCadastrarRemetenteActionPerformed
    {//GEN-HEADEREND:event_menuCadastrarRemetenteActionPerformed
        new SalvarRemetente().setVisible(true);
    }//GEN-LAST:event_menuCadastrarRemetenteActionPerformed

    /**
     * Le os dados do arquivo
     * @param filtro
     * @return ArrayList<String> contendo cada linha do arquivo
     */
    private ArrayList<String> buscaArquivo(FileNameExtensionFilter filtro)
    {
        try {
            buscaArquivo.setVisible(true);
            buscaArquivo.setFileFilter(filtro);

            int result = buscaArquivo.showOpenDialog(null); 

            if(result == JFileChooser.OPEN_DIALOG)
                return new ArquivoControl(buscaArquivo.getSelectedFile().toString()).getConteudoArquivoTexto();
        }
        catch (FileNotFoundException e) {
            JOptionPane.showMessageDialog(  
                                            this, 
                                            "Arquivo não encontrado"+
                                            "\nErro: "+e.getMessage()+
                                            "\nCausa: "+e.getCause(), 
                                            "Erro!", 
                                            JOptionPane.ERROR_MESSAGE
                                        );
            return null;
        }
        catch (IOException e) {
            JOptionPane.showMessageDialog(  
                                            this, 
                                            "Erro ao ler o arquivo"+
                                            "\nErro: "+e.getMessage()+
                                            "\nCausa: "+e.getCause(), 
                                            "Erro!", 
                                            JOptionPane.ERROR_MESSAGE
                                        );
            return null;
        }
        return null;
    }
    
    private void limpaTela()
    {
        textoNomeRemetente.setText("");
        textoEmailEnvio.setText("");
        textoUsuario.setText("");
        textoSenha.setText("");
        textoHostSmtp.setText("");
        textoPorta.setText("");
        checkAutenticacao.setSelected(true);
        textoMaximoEnvio.setText("");
        textoAssunto.setText("");
        textoMensagem.setText("");
        textoDestinatarios.setText("");
    }
    
    /**
     * Seta valores nos campos e reenvia o email
     * @param usuario
     * @param senha
     * @param hostSmtp
     * @param assunto
     * @param mensagem
     * @param porta
     * @param maximoEnvio
     * @param autenticacao
     * @param remetente
     * @param destinatarios 
     */
    public void reenvia (
                            RemetenteDadosDAO remetente,
                            MensagemModel mensagem,
                            String destinatarios
                        )
    {
        this.textoUsuario.setText(remetente.getUsuario());
        this.textoSenha.setText(remetente.getSenha());
        this.textoHostSmtp.setText(remetente.getHostSmtp());
        this.textoPorta.setText(String.valueOf(remetente.getPortaSmtp()));
        this.textoMaximoEnvio.setText(String.valueOf(remetente.getMaximoEnvio()));
        this.checkAutenticacao.setSelected(remetente.getAutenticacao());
        this.textoNomeRemetente.setText(remetente.getRemetente().getNome());
        this.textoEmailEnvio.setText(remetente.getRemetente().getEmail());
        
        this.textoAssunto.setText(mensagem.getAssunto());
        this.textoMensagem.setText(mensagem.getMensagem());
        
        this.textoDestinatarios.setText(destinatarios);
        
        botaoIniciarEnvio.doClick();
    }
    
    /**
     * Obtem os dados do Remetente
     * @return RemetenteDAO Dados do Remetente
     */
    private RemetenteDadosDAO obtemDadosRemetente()
    {
        return new RemetenteDadosDAO (
                                    new RemetenteDAO  (
                                                        textoEmailEnvio.getText(), 
                                                        textoNomeRemetente.getText()
                                                    ), 
                                    textoUsuario.getText(), 
                                    textoSenha.getText(), 
                                    textoHostSmtp.getText(), 
                                    Integer.parseInt(textoPorta.getText()), 
                                    Integer.parseInt(textoMaximoEnvio.getText()), 
                                    checkAutenticacao.isSelected()
                                );
    }
    
    /**
     * Obtém lista de destinatários
     * @return ArrayList<EmailModel> lista de destinatários
     */
    private ArrayList<DestinatarioDAO> obtemDestinatarios()
    {
        ArrayList<DestinatarioDAO> destinatarios   = new ArrayList<DestinatarioDAO>();

        for(String email: textoDestinatarios.getText().split("\n"))
        {
            destinatarios.add(new DestinatarioDAO(email));
        }
        
        return destinatarios;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane JScrollPane1;
    private javax.swing.JButton botaoIniciarEnvio;
    private javax.swing.JButton botaoProcurarDestinatarios;
    private javax.swing.JButton botaoProcurarMensagem;
    private javax.swing.JFileChooser buscaArquivo;
    private javax.swing.JCheckBox checkAutenticacao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenu menuCadastrar;
    private javax.swing.JMenuItem menuCadastrarRemetente;
    private javax.swing.JPanel painelConfiguracoesEmail;
    private javax.swing.JPanel painelDadosRemetente;
    private javax.swing.JPanel painelDestinatarios;
    private javax.swing.JTextField textoAssunto;
    private javax.swing.JTextArea textoDestinatarios;
    private javax.swing.JTextField textoEmailEnvio;
    private javax.swing.JTextField textoHostSmtp;
    private javax.swing.JTextField textoMaximoEnvio;
    private javax.swing.JTextArea textoMensagem;
    private javax.swing.JTextField textoNomeRemetente;
    private javax.swing.JTextField textoPorta;
    private javax.swing.JTextField textoSenha;
    private javax.swing.JTextField textoUsuario;
    // End of variables declaration//GEN-END:variables
    private FileNameExtensionFilter txtFilter   = new FileNameExtensionFilter("TXT Files (*.txt)", "txt");
    private FileNameExtensionFilter htmlFilter  = new FileNameExtensionFilter("HTML Files (*.html)", "html");
    
    private ArrayList<String> conteudoArquivo;
}
