/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.com.colmeiatecnologia.EmailMarketing.view;


import br.com.colmeiatecnologia.EmailMarketing.control.ArquivoControl;
import br.com.colmeiatecnologia.EmailMarketing.control.view.TextAreaControl;
import br.com.colmeiatecnologia.EmailMarketing.model.EmailModel;
import br.com.colmeiatecnologia.EmailMarketing.model.dao.DestinatarioDAO;
import br.com.colmeiatecnologia.EmailMarketing.model.dao.RemetenteDAO;
import br.com.colmeiatecnologia.EmailMarketing.model.dao.RemetenteDadosDAO;
import java.awt.Component;
import java.awt.Container;
import java.awt.event.ContainerEvent;
import java.awt.event.ContainerListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Rogério Eduardo Pereira <rogerio@groupsofter.com.br>
 * @version 1.0
 */
public class SalvarRemetente extends javax.swing.JFrame {

    /** Creates new form SalvarRemetente */
    public SalvarRemetente() {
        initComponents();
        addKeyAndContainerListenerRecursively(this);
        this.setLocationRelativeTo(null);
        textoNomeRemetente.requestFocus();
    }

    //BOTAO ESC E ENTER
    //LISTENERS DO FRAME
    //KEYLISTENER RECURSIVO (COLOCA EM TODOS OS COMPONENTES)
    private void addKeyAndContainerListenerRecursively(Component c) 
    {  
        try 
        {  
            c.addKeyListener((KeyListener) this);  
            if (c instanceof Container) 
            {  
                Container cont = (Container) c;  
                cont.addContainerListener((ContainerListener) this);  
                Component[] children = cont.getComponents();  
                for (int i = 0; i < children.length; i++) 
                {  
                    addKeyAndContainerListenerRecursively(children[i]);  
                }  
            }  
        } catch (Exception e) {  
            //Anuncie Aqui  
        }  
    }  
    
    //EVENTOS KEYLISTENER
    public void keyTyped(KeyEvent e) {}  
    public void keyReleased(KeyEvent e) {}  
    public void componentAdded(ContainerEvent e) {}  
    public void componentRemoved(ContainerEvent e) {}  
    public void keyPressed(KeyEvent e) 
    {
        //TECLA ESC
        if(e.getKeyCode() == KeyEvent.VK_ESCAPE)
        {
            
        }
        else if (e.getKeyCode() == KeyEvent.VK_ENTER)
        {
            
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        buscaArquivo = new javax.swing.JFileChooser();
        painelDadosRemetente3 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        textoNomeRemetente = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        textoEmailEnvio = new javax.swing.JTextField();
        painelConfiguracoesEmail3 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        textoHostSmtp = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        checkAutenticacao = new javax.swing.JCheckBox();
        jLabel26 = new javax.swing.JLabel();
        textoUsuario = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        textoSenha = new javax.swing.JTextField();
        textoPorta = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        textoMaximoEnvio = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        textoCodigo = new javax.swing.JTextField();
        painelDestinatarios = new javax.swing.JPanel();
        botaoProcurarDestinatarios = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        textoDestinatarios = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        botaoSalvar = new javax.swing.JButton();
        botaoEditar = new javax.swing.JButton();
        botaoRemover = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        comboBusca = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Remetentes");

        painelDadosRemetente3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Envio", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));

        jLabel22.setText("Nome");

        textoNomeRemetente.setPreferredSize(new java.awt.Dimension(14, 32));

        jLabel23.setText("E-mail Envio");

        textoEmailEnvio.setPreferredSize(new java.awt.Dimension(80, 32));

        painelConfiguracoesEmail3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Configurações Envio", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));

        jLabel24.setText("Host SMTP:");

        textoHostSmtp.setPreferredSize(new java.awt.Dimension(80, 32));

        jLabel25.setText("Porta");

        checkAutenticacao.setSelected(true);
        checkAutenticacao.setText("Autenticação SSL");

        jLabel26.setText("Usuário");

        textoUsuario.setPreferredSize(new java.awt.Dimension(80, 32));

        jLabel27.setText("Senha");

        textoSenha.setPreferredSize(new java.awt.Dimension(80, 32));

        textoPorta.setMinimumSize(new java.awt.Dimension(14, 32));
        textoPorta.setName(""); // NOI18N
        textoPorta.setPreferredSize(new java.awt.Dimension(14, 32));

        jLabel28.setText("Máximo Envios");

        textoMaximoEnvio.setPreferredSize(new java.awt.Dimension(14, 32));

        javax.swing.GroupLayout painelConfiguracoesEmail3Layout = new javax.swing.GroupLayout(painelConfiguracoesEmail3);
        painelConfiguracoesEmail3.setLayout(painelConfiguracoesEmail3Layout);
        painelConfiguracoesEmail3Layout.setHorizontalGroup(
            painelConfiguracoesEmail3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelConfiguracoesEmail3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelConfiguracoesEmail3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelConfiguracoesEmail3Layout.createSequentialGroup()
                        .addGroup(painelConfiguracoesEmail3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(jLabel25)
                            .addComponent(jLabel26)
                            .addComponent(jLabel27))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(painelConfiguracoesEmail3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textoPorta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textoHostSmtp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                            .addComponent(textoSenha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textoUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(painelConfiguracoesEmail3Layout.createSequentialGroup()
                        .addGroup(painelConfiguracoesEmail3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkAutenticacao)
                            .addGroup(painelConfiguracoesEmail3Layout.createSequentialGroup()
                                .addComponent(jLabel28)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textoMaximoEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        painelConfiguracoesEmail3Layout.setVerticalGroup(
            painelConfiguracoesEmail3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelConfiguracoesEmail3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelConfiguracoesEmail3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(textoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelConfiguracoesEmail3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(textoSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelConfiguracoesEmail3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(textoHostSmtp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelConfiguracoesEmail3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(textoPorta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkAutenticacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelConfiguracoesEmail3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(textoMaximoEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel29.setText("Código");

        textoCodigo.setEditable(false);
        textoCodigo.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        textoCodigo.setForeground(new java.awt.Color(255, 0, 0));
        textoCodigo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textoCodigo.setFocusable(false);
        textoCodigo.setPreferredSize(new java.awt.Dimension(30, 32));

        javax.swing.GroupLayout painelDadosRemetente3Layout = new javax.swing.GroupLayout(painelDadosRemetente3);
        painelDadosRemetente3.setLayout(painelDadosRemetente3Layout);
        painelDadosRemetente3Layout.setHorizontalGroup(
            painelDadosRemetente3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDadosRemetente3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelDadosRemetente3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelConfiguracoesEmail3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(painelDadosRemetente3Layout.createSequentialGroup()
                        .addGroup(painelDadosRemetente3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23)
                            .addComponent(jLabel29))
                        .addGap(24, 24, 24)
                        .addGroup(painelDadosRemetente3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textoEmailEnvio, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                            .addComponent(textoNomeRemetente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textoCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        painelDadosRemetente3Layout.setVerticalGroup(
            painelDadosRemetente3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelDadosRemetente3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelDadosRemetente3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(textoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelDadosRemetente3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(textoNomeRemetente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelDadosRemetente3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(textoEmailEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelConfiguracoesEmail3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painelDestinatarios.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Destinatários", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));

        botaoProcurarDestinatarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/colmeiatecnologia/EmailMarketing/view/img/zoom.png"))); // NOI18N
        botaoProcurarDestinatarios.setText("Procurar");
        botaoProcurarDestinatarios.setPreferredSize(new java.awt.Dimension(150, 32));
        botaoProcurarDestinatarios.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                botaoProcurarDestinatariosActionPerformed(evt);
            }
        });

        textoDestinatarios.setColumns(20);
        textoDestinatarios.setLineWrap(true);
        textoDestinatarios.setToolTipText("");
        textoDestinatarios.setWrapStyleWord(true);
        jScrollPane2.setViewportView(textoDestinatarios);

        javax.swing.GroupLayout painelDestinatariosLayout = new javax.swing.GroupLayout(painelDestinatarios);
        painelDestinatarios.setLayout(painelDestinatariosLayout);
        painelDestinatariosLayout.setHorizontalGroup(
            painelDestinatariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDestinatariosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelDestinatariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelDestinatariosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botaoProcurarDestinatarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)))
                .addContainerGap())
        );
        painelDestinatariosLayout.setVerticalGroup(
            painelDestinatariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDestinatariosLayout.createSequentialGroup()
                .addComponent(botaoProcurarDestinatarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                .addContainerGap())
        );

        botaoSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/colmeiatecnologia/EmailMarketing/view/img/dialog-accept.png"))); // NOI18N
        botaoSalvar.setText("Salvar");
        botaoSalvar.setPreferredSize(new java.awt.Dimension(150, 32));
        botaoSalvar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                botaoSalvarActionPerformed(evt);
            }
        });
        jPanel1.add(botaoSalvar);

        botaoEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/colmeiatecnologia/EmailMarketing/view/img/edit.png"))); // NOI18N
        botaoEditar.setText("Editar");
        botaoEditar.setPreferredSize(new java.awt.Dimension(150, 32));
        jPanel1.add(botaoEditar);

        botaoRemover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/colmeiatecnologia/EmailMarketing/view/img/edit-delete-2.png"))); // NOI18N
        botaoRemover.setText("Remover");
        botaoRemover.setPreferredSize(new java.awt.Dimension(150, 32));
        jPanel1.add(botaoRemover);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Busca", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));

        jLabel30.setText("Cliente");

        comboBusca.setPreferredSize(new java.awt.Dimension(73, 32));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboBusca, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(comboBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(painelDadosRemetente3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(painelDestinatarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(painelDadosRemetente3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelDestinatarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoProcurarDestinatariosActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botaoProcurarDestinatariosActionPerformed
    {//GEN-HEADEREND:event_botaoProcurarDestinatariosActionPerformed
        conteudoArquivo = new ArrayList<String>();
        conteudoArquivo = buscaArquivo(txtFilter);

        ArrayList<String> emailsvalidos = new ArrayList<String>();

        for(String email: conteudoArquivo)
        {
            if(EmailModel.validaEmail(email))
            emailsvalidos.add(email.trim().toLowerCase());
        }

        TextAreaControl.insereConteudo(textoDestinatarios, emailsvalidos);
    }//GEN-LAST:event_botaoProcurarDestinatariosActionPerformed

    private void botaoSalvarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botaoSalvarActionPerformed
    {//GEN-HEADEREND:event_botaoSalvarActionPerformed
        RemetenteDadosDAO remetente = new RemetenteDadosDAO (
                                                                new RemetenteDAO  (
                                                                                    textoEmailEnvio.getText(), 
                                                                                    textoNomeRemetente.getText()
                                                                                ), 
                                                                textoUsuario.getText(), 
                                                                textoSenha.getText(), 
                                                                textoHostSmtp.getText(), 
                                                                Integer.parseInt(textoPorta.getText()), 
                                                                Integer.parseInt(textoMaximoEnvio.getText()), 
                                                                checkAutenticacao.isSelected()
                                                            );
        if(!textoCodigo.getText().isEmpty())
            remetente.setCodigo(Long.parseLong(textoCodigo.getText()));
        
        remetente.setDestinatarios(obtemDestinatarios());
        
        try {
            remetente.salvar();
            JOptionPane.showMessageDialog(
                                            this, 
                                            "Salvo com Sucesso", 
                                            "Sucesso!", 
                                            JOptionPane.INFORMATION_MESSAGE
                                        );
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(  
                                            this, 
                                            "<html><body style='width: 200px;><p'>Erro ao Salvar</p>"+
                                            "<p><strong>Erro:</strong> "+e.getMessage()+"<br/>"+
                                            "<strong>Causa:</strong> "+e.getCause()+"</p></body></html>", 
                                            "Erro!", 
                                            JOptionPane.ERROR_MESSAGE
                                        );
        }
    }//GEN-LAST:event_botaoSalvarActionPerformed

    /**
     * Le os dados do arquivo
     * @param filtro
     * @return ArrayList<String> contendo cada linha do arquivo
     */
    private ArrayList<String> buscaArquivo(FileNameExtensionFilter filtro)
    {
        try {
            buscaArquivo.setVisible(true);
            buscaArquivo.setFileFilter(filtro);

            int result = buscaArquivo.showOpenDialog(null); 

            if(result == JFileChooser.OPEN_DIALOG)
                return new ArquivoControl(buscaArquivo.getSelectedFile().toString()).getConteudoArquivoTexto();
        }
        catch (FileNotFoundException e) {
            JOptionPane.showMessageDialog(  
                                            this, 
                                            "Arquivo não encontrado"+
                                            "\nErro: "+e.getMessage()+
                                            "\nCausa: "+e.getCause(), 
                                            "Erro!", 
                                            JOptionPane.ERROR_MESSAGE
                                        );
            return null;
        }
        catch (IOException e) {
            JOptionPane.showMessageDialog(  
                                            this, 
                                            "Erro ao ler o arquivo"+
                                            "\nErro: "+e.getMessage()+
                                            "\nCausa: "+e.getCause(), 
                                            "Erro!", 
                                            JOptionPane.ERROR_MESSAGE
                                        );
            return null;
        }
        return null;
    }
    
    private ArrayList<DestinatarioDAO> obtemDestinatarios()
    {
        //Destinatarios
        ArrayList<DestinatarioDAO> destinatarios   = new ArrayList<DestinatarioDAO>();
        
        if(textoDestinatarios.getText().isEmpty())
            return null;

        for(String email: textoDestinatarios.getText().split("\n"))
        {
            destinatarios.add(new DestinatarioDAO(email));
        }
        
        if(!destinatarios.isEmpty())
            return destinatarios;
        else 
            return null;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SalvarRemetente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SalvarRemetente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SalvarRemetente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SalvarRemetente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SalvarRemetente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoEditar;
    private javax.swing.JButton botaoProcurarDestinatarios;
    private javax.swing.JButton botaoRemover;
    private javax.swing.JButton botaoSalvar;
    private javax.swing.JFileChooser buscaArquivo;
    private javax.swing.JCheckBox checkAutenticacao;
    private javax.swing.JComboBox<String> comboBusca;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel painelConfiguracoesEmail3;
    private javax.swing.JPanel painelDadosRemetente3;
    private javax.swing.JPanel painelDestinatarios;
    private javax.swing.JTextField textoCodigo;
    private javax.swing.JTextArea textoDestinatarios;
    private javax.swing.JTextField textoEmailEnvio;
    private javax.swing.JTextField textoHostSmtp;
    private javax.swing.JTextField textoMaximoEnvio;
    private javax.swing.JTextField textoNomeRemetente;
    private javax.swing.JTextField textoPorta;
    private javax.swing.JTextField textoSenha;
    private javax.swing.JTextField textoUsuario;
    // End of variables declaration//GEN-END:variables

    private FileNameExtensionFilter txtFilter       = new FileNameExtensionFilter("TXT Files (*.txt)", "txt");
    private ArrayList<String>       conteudoArquivo;
}
